const {baseConfig} = require('@virmator/spellcheck/configs/cspell.config.base.cjs');

module.exports = {
    ...baseConfig,
    ignorePaths: [
        ...baseConfig.ignorePaths,
    ],
    words: [
        ...baseConfig.words,
        'audiosprite',
        'bbox',
        'cullable',
        'footguns',
        'hitbox',
        'hitboxes',
        'onfade',
        'onloaderror',
        'onplayerror',
        'onrate',
        'onseek',
        'onunlock',
        'onvolume',
        'pixi',
        'pixijs',
        'playerror',
        'singleplayer',
        'stunprotocol',
        'themself',
        'wasd',
        'webgpu',
        'vorbis',
        'flac',
        'weba',
    ],
};
